import React from 'react';
import { motion } from 'framer-motion';

const GalleryPage = () => {
  const mockImages = [
    { src: "https://image.pollinations.ai/prompt/A%20photorealistic%20exterior%20architectural%20render%20of%20a%20modern%20mansion%20with%20a%20pool%20at%20twilight?width=800&height=600&nologo=true", alt: "Modern Mansion" },
    { src: "https://image.pollinations.ai/prompt/A%20cozy%20scandinavian%20living%20room%20interior%20with%20a%20fireplace%20and%20large%20windows?width=800&height=600&nologo=true", alt: "Scandinavian Interior" },
    { src: "https://image.pollinations.ai/prompt/A%20modern%20scandinavian%20house%20exterior%20concept?width=800&height=600&nologo=true", alt: "Scandinavian Exterior" },
    { src: "https://image.pollinations.ai/prompt/A%20classic%20luxury%20mediterranean%20villa%20exterior%20with%20terracotta%20roof?width=800&height=600&nologo=true", alt: "Mediterranean Villa" },
    { src: "https://image.pollinations.ai/prompt/A%20minimalist%20japanese%20zen%20bedroom%20interior?width=800&height=600&nologo=true", alt: "Zen Bedroom" },
    { src: "https://image.pollinations.ai/prompt/A%20modern%20industrial%20loft%20living%20room%20with%20exposed%20brick?width=800&height=600&nologo=true", alt: "Industrial Loft" },
  ];

  return (
    <div className="pt-32 px-6 max-w-7xl mx-auto min-h-screen">
      <div className="text-center mb-16">
        <h1 className="text-5xl md:text-7xl font-display font-bold mb-6">Inspiration Gallery</h1>
        <p className="text-xl text-gray-soft max-w-2xl mx-auto">
          Explore stunning concepts generated by our community using AI Home Designer.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 pb-20">
        {mockImages.map((img, idx) => (
          <motion.div 
            key={idx}
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: idx * 0.1 }}
            className="rounded-3xl overflow-hidden border border-white/10 group relative aspect-[4/3]"
          >
            <img 
              src={img.src} 
              alt={img.alt} 
              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6">
              <p className="text-white font-bold text-lg">{img.alt}</p>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
};

export default GalleryPage;
